name: quickrun-c CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        cache: 'pip' # caching pip dependencies
    - run: pip install cpplint==1.6.1
    - run: make lint

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: make

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/googletest/ && sudo mkdir build && cd build && sudo cmake .. && sudo make && sudo make install
    - run: make -B test
    - name: Generate a code coverage report
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        cache: 'pip' # caching pip dependencies
    - run: pip install gcovr==7.2
    - run: gcovr -e tests --cobertura coverage.xml

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '1 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md